### ISSUE TITLE
Query the value of a macro

### ISSUE THREAD

**Issue by hemmer** [google/gin-config#11]
Is it possible to query the value of a macro? I have tried:

```
gin.parse_config("my_macro = 3")
print(gin.query_parameter("my_macro"))
```
to which I get the message:
`ValueError: No configurable matching 'my_macro'.`

Same occurs for `print(gin.query_parameter("gin.macro.my_macro"))` or `print(gin.query_parameter("%my_macro"))`

**Comment by colllin** [comment]
I think there's actually a bug here — not necessarily in querying the value of a macro, but I'm unable to query the value defined by the macro where it's used, either:

```python
my_macro = 5
my_function.my_arg = %my_macro

...

gin.query_parameter('my_function.my_arg') # returns '%my_macro'
```

**Comment by sguada** [comment]
You should be able to query the value of a macro by doing
`
gin.query_parameter('my_macro/macro.value')
`
I added an easier way to query it, but need to push them change.

gin.query_parameter('%my_macro')

To be able to bind macros you need to call 
gin.finalize()

**Comment by sguada** [comment]
Open again if needed.
