### ISSUE TITLE
Enum constants not reloaded after clear_config

### ISSUE THREAD

**Issue by MistaGiggles** [google/gin-config#12]
I ran into a rather confusing issue related to using constants_from_enum decorator and gin.clear_config(clear_constants=True). In my code there is a loop over multiple parameter sets that clears the configuration and constants before reparsing the input file.

My enum was defined in a separate file which is imported by the config file. The decorator is executed and the constants are added to _CONSTANTS. Once `clear_config(clear_constants=True) `is called these constants are removed.
`parse_config` is called again, but this time `mymodule` has already been imported and is skipped. This means that the decorator is not run again and the enum constants are missing from _CONSTANTS and gin complains that a macro is missing a value.

This problem can be avoid by setting `clear_constants=False`, but perhaps gin could prevent this issue by treating enum constants as a special case and not clearing them out?

Below is an example recreating the issue

mymodule.py:
```
import enum
import gin

@gin.constants_from_enum
class MyEnum(enum.Enum):
    A = 1
    B = 2
```

main.py:
```
import gin
#mymodule can be imported here, with a similar effect

@gin.configurable
def myfunc(value):
    print(value)

for i in range(3):
	gin.clear_config(clear_constants=True)
	gin.parse_config([
		'import mymodule',
		'myfunc.value = %MyEnum.B'
	])

	myfunc()
```

**Comment by sguada** [comment]
I think calling `gin.clear_config()` does what you want, keeps the _CONSTANTS defined, since it has `clear_constants=False` by default.
