### ISSUE TITLE
Release latest version of gin on pypi

### ISSUE THREAD

**Issue by valentindey** [google/gin-config#136]
The latest release on pypi is v4.0.0 from Nov 24, 2020. There is some functionality added since then that I require (https://github.com/google/gin-config/pull/116).

Installing from github is not a (easy) solution for me at some places. I'd prefer having the recent version of gin released on pypi.

In order to avoid manual work, is this something that could be automated for future releases?

**Comment by valentindey** [comment]
ping @sguada

**Comment by MoritzTaylor** [comment]
Any news on this? @sguada

**Comment by sguada** [comment]
v.0.5 is available https://pypi.org/project/gin-config/
