### ISSUE TITLE
Assign parameters in gin file to new variables in a different script

### ISSUE THREAD

**Issue by jdubkim** [google/gin-config#141]
Hi, I created a gin file for train.py, and stored configurations into .gin file using gin.config_str(). 
I would like to load these configurations into a different script play.py.
For example, in my config.gin, I assigned train.agent = @PPO(), and in play.py, I would like to assign an agent in play function to @PPO() as well. Is there a way to do this?

**Comment by ppo** [comment]
Who had the brilliant idea to use `ppo` as decorator name!? 🙄😂

**Comment by jdubkim** [comment]
ppo is a name of a RL algorithm.

**Comment by ppo** [comment]
@jdubkim It was just stupid humor 😉
