### ISSUE TITLE
why I can't use @ ?

### ISSUE THREAD

**Issue by huxiaobo007** [google/gin-config#161]
I always get an error when using the @ symbol in the .gin file
for example:
when I uesd dnn.activation_fn = @tf.nn.tanh;
ValueError: No configurable matching reference '@tf.nn.tanh'
Whatever @ I use  , I always get the error.

**Comment by akjskakjsas** [comment]
I meet this issue too!!!

**Comment by sguada** [comment]
Yeah you need to `import gin.tf.external_configurables`
