### ISSUE TITLE
Unexpected keyword argument 'whitelist'

### ISSUE THREAD

**Issue by apbyju** [google/gin-config#170]
@gin.configurable(whitelist=[]) when added to the code
TypeError: configurable() got an unexpected keyword argument 'whitelist'

**Comment by wrtnew** [comment]
I have met same problem when used disentangle_lib 
TypeError: configurable() got an unexpected keyword argument 'blacklist'
I guessed that it has changed to denylist and allowlist.

**Comment by LazyRacc00n** [comment]
@wrtnew, how did you solve the problem to use disentangle_lib? thanks

**Comment by sguada** [comment]
Need to use `denylist` and `allowlist`

**Comment by epignatelli** [comment]
> Need to use `denylist` and `allowlist`

Since what version?

**Comment by epignatelli** [comment]
For the posterity, version `0.4.0` is the last version with `blacklist` in place of `denylist`
