### ISSUE TITLE
Registered constants in operative_str?

### ISSUE THREAD

**Issue by domkirke** [google/gin-config#173]
Hello, 
I don't know if it would come against the gin-config philosophy, but I am facing a simple issue that I am not able to resolve with the current functionalities. Let say I have a GIN config file requiring initialization value, such that in a `.gin` file I got something like : 
```gin
very_important_macro = %init_value
```
that has to be defined in the main python file : 
```python
gin.constant('init_value', 20)
gin.parse_config_file()
```

the `very_important_macro` is indeed correctly parsed, but absent from the finalized `gin.operative_config_str()`, such that the value is lost when the configuration is saved (for further reloading). Wouldn't it be possible to write constants in operative string, or did I miss something?

Amazing work nonetheless ;)

**Comment by sguada** [comment]
Thanks, if you use `gin.bind_parameter` instead of `gin.constant` you will get the value recorded.

```
very_important_macro = %init_value
```
```
gin.bind_parameter('%init_value', 20)
gin.parse_config_file()
```

```
print(gin.config_str())
# Macros:
# ==============================================================================
init_value = 20
very_important_macro = %init_value
```
