### ISSUE TITLE
can't bind/rebind constant after parsing config

### ISSUE THREAD

**Issue by leomao** [google/gin-config#18]
Consider a macro is referenced in a config but not bound in that config.  One may want to specify that constant in the program after parsing the config.  For example, consider a configurable function:
```
@gin.configurable
def func(x):
    return x
```
and the configuration:
```
gin.parse_config('func.x = %num')
gin.constant('num', 20)

func() # error
```
Currently, the code above will cause `No values supplied by Gin or caller for arguments: ['value']`.  On the other hand, the following code snippet work as expected:
```
gin.constant('num', 20)
gin.parse_config('func.x = %num')

func() # get 20
```
Note that if we bind the macro in the config and rebind it using `gin.constant` afterward:
```
gin.parse_config('''
func.x = %num
num = 10
''')
gin.constant('num', 20)

func() # get 10 instead of 20
```
It seems that `gin.constant` doesn't affect the config that is parsed before it.  I think this behavior is a bug...?

**Comment by sguada** [comment]
The idea of defining a `gin.constant` is to be constant.
But you may try `gin.bind_parameter('%num', 20)`

**Comment by leomao** [comment]
Thanks!  Didn't know that `bind_parameter` can use `%num` syntax sugar.  The idea of constant is reasonable.
