### ISSUE TITLE
Gin Breaks Jupyter Module Reload

### ISSUE THREAD

**Issue by xanderdunn** [google/gin-config#23]
I'm using gin in a Jupyter notebook and I'm unable to reload a module when I've made changes to it.  I'll get an error that the configurables already exist: `ValueError: A configurable matching 'main.get_train_envs' already exists.`

I tried running this before doing a module reload:
```
tf.reset_default_graph()
gin.config.clear_config()
```
But this doesn't work because it doesn't clear the gin registry.  

This is a real pain because it requires me to restart my Jupyter kernel and re-run every cell in my notebook on any change to any dependency.  Typically this is unnecessary in Jupyter notebook development.  Modules can be automatically reloaded with:
```
%load_ext autoreload
%autoreload 2
```

Or manually with:
```
import importlib
importlib.reload(some_module)
```

**Comment by sguada** [comment]
You can use `gin.enter_interactive_mode()`

See https://github.com/google/gin-config/blob/master/gin/gin_intro.ipynb

**Comment by xanderdunn** [comment]
This works for me, thanks a lot!
