### ISSUE TITLE
[Feature Requests] Support configuration aliases / names that persist through code refactoring

### ISSUE THREAD

**Issue by yzhuang** [google/gin-config#27]
Hello project maintainers,

We started evaluating gin-config for wider use in some of our projects. One thing I noticed is that gin config files are tied to symbol names in code (i.e. class names and function names). 

In repositories with high change velocity, refactoring class and function names tend to break their associated config files. Could you provide a functionality to specify stable aliases for configuration names? For example, like this:

```
@gin.configurable(alias=model_training_config)
def train_model(learning_rate):
  pass
```

```
model_training_config.learning_rate=0.001
```

The goal is that when we refactor and change the function name, it's associated configuration should not break.  This functionality is usually available in dependency injection frameworks in general.

Thank you very much for your time.

-Yi

**Comment by jackd** [comment]
I'm not a project maintainer, but if I understand your request correctly it's already supported:

```python
import gin


@gin.configurable('model_training_config')
def train_model(learning_rate):
  print('learning_rate = {}'.format(learning_rate))


config = 'model_training_config.learning_rate=0.001'

gin.parse_config(config)
train_model()
```

**Comment by yzhuang** [comment]
Somehow we failed to discover this. Thank you very much for spending time to reply. 
Closing the request since the question is answered.

**Comment by sguada** [comment]
Thanks @jackd for providing the answer. Yeah you can name configurables and also specify their module, so you can even group configurables across files. Example
```python
@gin.configurable('model_training', module='config')
def train_model(learning_rate):
  print('learning_rate = {}'.format(learning_rate))

@gin.configurable('model_testing', module='config')
def test_model(epochs=1):
  ...

config = '''
    config.model_training.learning_rate=0.001
    config.model_testing.epochs=2
'''

**Comment by yzhuang** [comment]
Thanks for the above example @sguada , it was very helpful.
