### ISSUE TITLE
List of external configurables

### ISSUE THREAD

**Issue by miguelvr** [google/gin-config#28]
Is it possible to pass a list of external configurables in the gin configuration?

Something on the lines of:

```python
build_transforms.transforms_list = [
    @transform1,
    @transform2,
    @transform3
]

transform1.param = 1
transform3.other_param = 2
```

And if not, is there any way of achieving a similar result?

I need to be able to control the data transforms pipeline and set each transform's parameters individually

**Comment by miguelvr** [comment]
manage to solve the problem!

Solution:

```
build_transforms.transforms_list = [
    @transform1(),
    @transform2(),
    @transform3()
]

transform1.param = 1
transform3.other_param = 2
```

**Comment by sguada** [comment]
Both are valid ways to pass configurables, although they have different meanings. In the first case you are passing the references, if they are callables you would need to call them inside `build_transforms`. In the second case the transformations are build first and the passed to the `build_transforms`.
