### ISSUE TITLE
gin provided objects not pickable

### ISSUE THREAD

**Issue by besterma** [google/gin-config#31]
Using gin configs for a multiprocessing process providing a class as input leads to a pickle error when using the spawn start method. Following minimal example probably explains the problem better:
<details>
  <summary>Code</summary>
  
  ```python
import multiprocessing as mp
import gin


@gin.configurable('example_process')
class Process(mp.Process):
    def __init__(self, input_class):
        super().__init__()
        self.input_class = input_class
        print("Init Process")

    def run(self):
        print("Hello World!")


@gin.configurable()
class A:
    pass


if __name__ == "__main__":
    mp.set_start_method('spawn')
    gin.parse_config('example_process.input_class = @A')

    process_1 = Process(A)
    process_1.start()
    process_1.join()

    process_2 = Process()
    process_2.start()
    process_2.join()
```
</details>

process_1 runs fine whereas process_2 fails with error
`
_pickle.PicklingError: Can't pickle <class '__main__.A'>: it's not the same object as __main__.A
`

Is there a way to solve this problem? I really need to use the spawn method, fork does not work for different reasons.

I am running python 3.7.4 with gin 0.2.1

Thanks and best,
besterma

**Comment by besterma** [comment]
A follow up question regarding the multi process case:
What is the best way to make a gin config available to a newly spawned process? 
Passing on the `gin.config_str()` and freshly parsing it in the child process alone is not enough, as the external_configurables are not included.

**Comment by gmrukwa** [comment]
I have similar problems with pickling. To be exact, I want my sklearn-alike estimators to be `@gin.configurable`, but then these are not picklable, which completely misses the point. I found out that [here](https://github.com/google/gin-config/blob/master/gin/config.py#L310) a class is substituted. According to [that SO answer](https://stackoverflow.com/a/52186874), such an approach doesn't work with pickling at all. Similar scenario occurs for each `gin.external_configurable`.
I see that it is explicitly stated to create a class in these scenarios. Is there any specific reason for that? Simple change of the `True` to `False` immediately resolves picklability problem, but I'm not sure if it doesn't create other problems.

**Comment by besterma** [comment]
It has been a while, but if I remember correctly, I pass the gin config as a string (`gin.config_str()`) as an argument to the new process and then parse it again after spawning of the process (`gin.parse_config(self.gin_string)`)

**Comment by YvanYin** [comment]
@besterma  Thx a lot. Your method can transfer the config to the new spawned  process, but some functions still cannot access the config. I will try to figure out.
