### ISSUE TITLE
unable to leverage imports due to 'Failed to parse token' ; SyntaxError: Expected '='. ; ModuleNotFoundError: No module named ; SyntaxError: malformed node or string

### ISSUE THREAD

**Issue by bionicles** [google/gin-config#33]
We'd like to configure our modular project with gin but the imports always break:

`import nature`

```
  File "config.gin", line 3
    FC = nature.FC
        ^
SyntaxError: malformed node or string: <_ast.Name object at 0x7f5aeb65b0f0>
    Failed to parse token 'nature'
```

`from nature import *`
```
  File "config.gin", line 1
    from nature import *
        ^
SyntaxError: Expected '='.
```

`import nature.bricks.built_in.fc.FC`
```
ModuleNotFoundError: No module named 'nature.bricks.built_in.fc.FC'; 'nature.bricks.built_in.fc' is not a package
  In file "config.gin", line 1
    import nature.bricks.built_in.fc.FC
```

`import nature.bricks.built_in.fc`
```

  File "config.gin", line 23
    Layer.layer_fn = fc.FC
                    ^
SyntaxError: malformed node or string: <_ast.Name object at 0x7fa62799bba8>
    Failed to parse token 'fc'
```

FC is decorated with @gin.configurable and we import nature in the normal python file which invokes `gin.parse_config_file`

maybe if "gin" files were .py files, then the imports would work, but as it stands, gin doesn't work like normal python because it's a separate/reinvented format, and thus always fails on imports, aliases, functions

**Comment by sguada** [comment]
Can you copy and paste your full gin config file, the errors seems related to import errors, as that Python cannot import those modules.
