### ISSUE TITLE
Load gin config to 1 function or as a dict

### ISSUE THREAD

**Issue by chledowski** [google/gin-config#34]
Hi. Thanks for your nice work.

I am using gin to configure my experiments. Next, while visualizing results in a Jupyter Notebook, I would like to be able to load only my model parameters from the `.gin` file. 

Is there a way to just load the `.gin` params to only one function? Or just to load it as a dict?

Thanks :)

**Comment by sguada** [comment]
I'm not sure what you mean, you can just load the .gin file as a text file. Not clear how to load as dict.

**Comment by chledowski** [comment]
I was just curious if there is a way to easily parse the file into a dict. 

Anyway, I just realized that a workaround that works for me is deleting parts of config file I don't need :)
