### ISSUE TITLE
Example of using the command line functionality

### ISSUE THREAD

**Issue by caseyjconger** [google/gin-config#55]
Do you think you guys could provide an example of passing configurable parameters via command line?

Regardless, thank you to everyone involved with gin-config! I had been hacking something together along these lines but you guys came along and saved me a lot of effort producing something that does half as much. Great work!

**Comment by sguada** [comment]
So to pass configurable parameters via command line, just define FLAG and then parse it with 
```
gin.parse_config_files_and_bindings(FLAG.gin_files, bindings=FLAG.gin_bindings)
```
For an example see:
https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/train.py

**Comment by Mageswaran1989** [comment]
I am keep getting "SyntaxError: Expected newline.", when I use above suggested solution.
