### ISSUE TITLE
Easy way to export all configuration variables into JSON/Dictionary?

### ISSUE THREAD

**Issue by bfortuner** [google/gin-config#6]
I would like to store all the configuration values stored in gin at runtime (files, function constants, etc) in my postgres database. Is there an easy way to export everything gin is holding at runtime?

**Comment by sguada** [comment]
You can use 'gin.operative_config_str()'

**Comment by wookayin** [comment]
What about default parameters that were not binded through gin?

**Comment by sguada** [comment]
'gin.operative_config_str()' would list all the default parameters of the `gin.configurable` functions that have been used, even if those parameters were not binded through gin.
