### ISSUE TITLE
Getting "no module named gin.torch" when doing "import gin.torch"

### ISSUE THREAD

**Issue by pseeth** [google/gin-config#63]
I set up a new environment using this sequence of commands:

    conda create -n test-gin python=3.7
    conda activate test-gin
    pip install torch
    pip install gin-config
    python -c "import gin.torch"

This results in the following:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'gin.torch'

Unsure what's going wrong.

Thanks in advance for the help! ``gin`` is quite cool and working well for me otherwise.

**Comment by sguada** [comment]
Try installing directly from github, we need to push a new pip package.
```
pip install git+https://https://github.com/google/gin-config
```

**Comment by pseeth** [comment]
Great, it works! Thanks.
