### ISSUE TITLE
[bug] gin.REQUIRED ignored when default value of a keyword arg

### ISSUE THREAD

**Issue by lamblin** [google/gin-config#7]
When a function decorated with `@gin.configurable` is passed `gin.REQUIRED`, not as an explicit value but as the default value of a keyword argument, it does not raise a `RuntimeError`, but happily uses the string value `'__gin_required__'`.

For instance, using a slight modification of an example on https://github.com/google/gin-config/blob/master/gin/gin_intro.ipynb:
```python
gin.clear_config()

@gin.configurable
def say_hello(name=gin.REQUIRED):
  print("Hello %s!" % name)

try:
  say_hello()
except RuntimeError as e:
  print('Error message (gin.REQUIRED):', e)
```
Actual output:
```
Hello __gin_required__!
```
Expected output:
```
Error message (gin.REQUIRED): Required bindings for `say_hello` not provided in config: ['name']
```

Note that explicitly passing `gin.REQUIRED` works as expected:
```python
try:
  say_hello(gin.REQUIRED)
except RuntimeError as e:
  print('Error message (gin.REQUIRED):', e)
```
produces the expected output:
```
Error message (gin.REQUIRED): Required bindings for `say_hello` not provided in config: ['name']
```

I understand that in such a simple case, I could just declare `def say_hello(name)` and let Python complain about the missing argument. However, it would be really useful to be able to essentially mark a keyword argument as required through `gin`. Moreover, it is really surprising to have different behaviors when the argument is passed explicitly vs. implicitly.

This happened with the latest development version.

**Comment by sguada** [comment]
Thanks for the requests, a few others have also asked for this and we are working on it.

Although contributions are welcomed.

**Comment by MarekAtGoogle** [comment]
I believe this has been implemented and will be available in the next update.

**Comment by sguada** [comment]
This should work now, re-open if that is not the case.
