### ISSUE TITLE
Overwriting a value back to gin config file

### ISSUE THREAD

**Issue by justanhduc** [google/gin-config#81]
My code automatically makes a folder when running an experiment. If I want to resume training, I have to manually specify the checkpoint folder to the gin-config file. Is there any way to write this checkpoint path into gin-config after the experiment runs? Thanks!

**Comment by corynezin** [comment]
Maybe the easiest way to do this would be to write to an external file and use that configure gin:

```
getfile.path = 'test.txt'
echo.a = @getfile()
```

```py
import gin

@gin.configurable
def echo(a):
    print(a)

@gin.register
def getfile(path):
    with open(path) as f:
        return f.read().strip()

gin.parse_config_file('config.dev.gin')
echo()
```

**Comment by sguada** [comment]
You can also pass the folder name via command line configuration using gin parameter, ex:

```
flags.DEFINE_string('root_dir', os.getenv('TEST_UNDECLARED_OUTPUTS_DIR'),
                    'Root directory for writing logs/summaries/checkpoints.')
FLAGS = flags.FLAGS

gin.bind_parameter('experiment.folder', FLAGS.root_dir)
```

Or just bind the value of the folder in the code when it runs.

```
flags.DEFINE_string('root_dir', os.getenv('TEST_UNDECLARED_OUTPUTS_DIR'),
                    'Root directory for writing logs/summaries/checkpoints.')
FLAGS = flags.FLAGS

gin.constant('ROOT_DIR', FLAGS.root_dir)
```
