### ISSUE TITLE
Skip Unknown ignoring @gin.register

### ISSUE THREAD

**Issue by jesseengel** [google/gin-config#82]
Hi! I've got a lot of functions decorated with `@gin.register` in [ddsp](https://github.com/magenta/ddsp), and I recently removed a kwarg from one of those functions (delta_delta_time_weight from spectral_ops.SpectralLoss). My operative_config for a pretrained model still has the old kwargs in it's config:

```
.
.
.
# Parameters for SpectralLoss:
# ==============================================================================
SpectralLoss.delta_delta_freq_weight = 0.0
SpectralLoss.delta_delta_time_weight = 0.0
.
.
.
```

but when I try to load the gin config with the new codebase that doesn't have the kwarg, it throws an error even though I use skip_unknown=True.

Command:
```
with gin.unlock_config():
  gin.parse_config_file(gin_file, skip_unknown=True)
```

Error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-2893e878fb89> in <module>()
     55 # Parse gin config,
     56 with gin.unlock_config():
---> 57   gin.parse_config_file(gin_file, skip_unknown=True)
     58 
     59 # Assumes only one checkpoint in the folder, 'ckpt-[iter]`.

9 frames
/usr/local/lib/python3.6/dist-packages/gin/config.py in __new__(cls, binding_key)
    515     if not _might_have_parameter(configurable_.fn_or_cls, arg_name):
    516       err_str = "Configurable '{}' doesn't have a parameter named '{}'."
--> 517       raise ValueError(err_str.format(selector, arg_name))
    518 
    519     if configurable_.whitelist and arg_name not in configurable_.whitelist:

ValueError: Configurable 'SpectralLoss' doesn't have a parameter named 'delta_delta_freq_weight'.
  In file "/content/pretrained/operative_config-0.gin", line 92
    SpectralLoss.delta_delta_freq_weight = 0.0
```

As far as I understand, this is the use case of `skip_unknown` correct? Is it missing it because SpectralLoss is an object wrapped in `@gin.register` instead of `@gin.cofigurable`? Is there a way to avoid this error without requiring modifying the gin config file itself?

**Comment by sguada** [comment]
I using `skip_unknown=True` is for cases where the function itself is not registered and unknown, but not for argument mismatches.

**Comment by jesseengel** [comment]
I see, is there any option then for when the function signature changes, or is my only option to put the kwargs back in or change the original gin files?

**Comment by sguada** [comment]
Good question, we don't currently have any mechanism for that. Not sure how hard or useful would be to add a mechanism for deprecated parameters, something similar to what TF has.

**Comment by jesseengel** [comment]
Not sure if it's helpful, but for DDSP I hacked together a script to update gin configs: https://github.com/magenta/ddsp/pull/167

It basically has options to remove lines, add lines, and do line-by-line substitutions.

**Comment by sguada** [comment]
If you are interested in creating a slightly more general solution, I think having a small tool to update gin config files would be really helpful for many users.

**Comment by jesseengel** [comment]
Yah, that would be cool, only two barriers (1) I'm just not sure about what API would make sense for the general use case (the current one pretty hacky with a couple global lists in the script itself. (thoughts?) (2) Unfortunately, I honestly don't have the bandwidth right now to maintain such a general tool separate to DDSP, but could contribute it if someone else took on maintenance / improvement of the tool.

**Comment by jesseengel** [comment]
fwiw, the script I wrote is now here: https://github.com/magenta/ddsp/blob/master/update_gin_config.py
