### ISSUE TITLE
Document / add external API for `_INTERACTIVE_MODE` [Enhancement]

### ISSUE THREAD

**Issue by neighthan** [google/gin-config#92]
I've been using some classes that are `gin.configurable` in Jupyter notebooks while running the `autoreload` extension. This leads to issues whenever a `gin.configurable` class is redefined. Throwing these errors in scripts seems reasonable, but for a Jupyter session, I'd like to be able to turn them off. Looking in the code a bit, I found these errors can be suppressed by setting `gin.config._INTERACTIVE_MODE = True`. This feels like an internal mechanism which thus isn't necessarily going to continue existing in the future. It would be nice to 1) create a proper way to do this (e.g. `gin.enable_interactive_mode()`) and 2) document this option in the user guide. This seems like it should be pretty easy, so I'd be happy to submit a PR if it would be accepted.

**Comment by sguada** [comment]
You can add `gin.enter_interactive_mode()` to your Jupiter notebook as done [here](https://github.com/google/gin-config/blob/5c0f63c68811f969c0944d1164cbe710211564f6/gin/gin_intro.ipynb)

If you want to expand the docs to make it more clear, please send a PR.

**Comment by neighthan** [comment]
Ah, sorry, I thought I'd checked `gin.` for anything with "interactive" in it, but apparently I missed this. I'll leave this open for now and try to add something to the docs when I have time.
